# create pod & expose service
#steps: 
#namespce-create
#create pod in namespce
#expose service (type:NodePort) to access service from outside the cluster

#namespace create
apiVersion: v1
kind: Namespace

















#commands
#kubectl api-resources