#here i am creating namespace for my first-pod

apiVersion: v1   #api version of ns,   command: cubectl api resources
kind: Namespace      #object type , same command , it define type of k8s resource being use
metadata:
    name: first-pod      #pod name
    labels: 
         app: nginx 
         env: dev
    namespace: evc-prod-ns    #namspace where pod should create
spec:     #here we have to specify pod-->container specification.
  containers: 
  - name: first-pod-container1
    image: nginx
    ports: 
    - name: http
      containerPort: 80           #default port of nginx
           
