# create pod & expose service
#steps: 
#namespce-create
#create pod in namespce
#expose service (type:NodePort) to access service from outside the cluster

#namespace create
apiVersion: v1
kind: Namespace
metadata:
    name: evc-ns
    labels:
       app: evc-app
       env: dev


#create pod in namespce
apiVersion: v1
kind: Pod 

metadata:
   name: evc-pod
   labels:
       app: evc-app
       env: dev
names
spec:
 containers: 
  - name: evc-pod-c1
    image: nginx
    ports: 
    - name: http
      containerPort: 80           #default port of nginx
                  

#expose service












#commands
#kubectl api-resources