#here i am exposing  service to get application access over external natewok.

# configure kind : kind indicates the type of Kubernetes resource being defined 
apiVersion: v1   
kind: Service      
metadata:
    name: first-pod-svc
    labels: 
         app: evc-app 
         env: dev
         
    namespace: evc-prod-ns  

 # configure spec: spec defines the desired state of the resource (specify resources want to create & manage)    
spec: 
  type: NodePort        #service type
  salector:             # Label selector to match Pods for this service
    app: evc-app        #
  port: 80


  containers: 
  - name: first-pod-container1
    image: nginx
    ports: 
    - name: http
      containerPort: 80           #default port of nginx
           

spec:
  type: NodePort
  selector:
    app: eb-ms-app #[app: eb-ms-app]
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: tomcat-port
      protocol: TCP
      port: 8080
      targetPort: 8080  
           cubectl expose pod first-pod -n evc-prod-ns --type NodePort -- port 80 --targetPort 8081