#here i am exposing  service to get application access over external natewok.

# configure kind : kind indicates the type of Kubernetes resource being defined 
apiVersion: v1   
kind: Service      
metadata:
    name: first-pod-svc
    labels: 
         app: nginx 
         env: dev
    namespace: evc-prod-ns  

 # configure spec: spec defines the desired state of the resource (specify resources want to create & manage)    
spec: 
  type: NodePort        #service type
  port:

  containers: 
  - name: first-pod-container1
    image: nginx
    ports: 
    - name: http
      containerPort: 80           #default port of nginx
           

           cubectl expose pod first-pod -n evc-prod-ns --type NodePort -- port 80 --targetPort 8081