#here i am exposing  service to get application access over external natewok.

# configure kind : kind indicates the type of Kubernetes resource being defined 
apiVersion: v1   
kind: Service      
metadata:
    name: first-pod-svc
    labels: 
         app: evc-app 
         env: dev
         
    namespace: evc-prod-ns  

 # configure spec: spec defines the desired state of the resource (specify resources want to create & manage)    
spec: 
  type: NodePort        #service type
  selector:             # Selects the set of Pods targeted by this Service.
    app: evc-app        #label
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081


           

#commands
#kubectl api-resources
#cubectl expose pod first-pod -n evc-prod-ns --type NodePort -- port 80 --targetPort 8081
#kubectl get nodes -n evc-prod-ns -o wide   OR minikube ip