#here i am exposing  service to get application access over external natewok.
# configure kind ( what to create)
apiVersion: v1   
kind: Service      
metadata:
    name: 
    labels: 
         app: nginx 
         env: dev
    namespace: evc-prod-ns    #namspace where pod should create
spec:     #here we have to specify pod-->container specification.
  containers: 
  - name: first-pod-container1
    image: nginx
    ports: 
    - name: http
      containerPort: 80           #default port of nginx
           